### ISSUE TITLE
compiler-bridge_2.11 does not compile with Scala 2.11.0

### ISSUE THREAD

**Issue by eed3si9n** [sbt/zinc#276]
## steps

1. Use latest zinc to compile 2.11. 

https://github.com/eed3si9n/sbt/tree/wip/bump_modules has the code to run:

> scripted compiler-project/separate-analysis-per-scala

## problem

See https://travis-ci.org/sbt/sbt/jobs/214319964.

```
[info] [info] Compiling 1 Scala source to /tmp/sbt_cb8e31c7/separate-analysis-per-scala/target/scala-2.11/classes ... (out-18) (out-1)
[info] [info] Non-compiled module 'compiler-bridge_2.12' for Scala 2.11.0. Compiling... (out-18) (out-1)
[error] /tmp/sbt_35b33db3/xsbt/CompilerInterface.scala:159: error: class Compiler needs to be abstract, since method PerRunReporting in trait Reporting of type => Compiler.this.PerRunReporting is not defined (out-1)
[error]   class Compiler extends CallbackGlobal(command.settings, dreporter, output) { (out-1)
[error]         ^ (out-1)
[error] /tmp/sbt_35b33db3/xsbt/ScaladocInterface.scala:45: error: object creation impossible, since method PerRunReporting in trait Reporting of type => xsbt.Runner.forScope.DocFactory.compiler.PerRunReporting is not defined (out-1)
[error]       object compiler extends Global(command.settings, reporter) with GlobalCompat { (out-1)
[error]              ^ (out-1)
[error] two errors found (out-1)
[info] [info] Attempting to fetch org.scala-sbt % compiler-bridge_2.12 % 1.0.0-X11. This operation may fail. (out-18) (out-1)
[info] [error] (compile:compileIncremental) Error compiling the sbt component 'compiler-bridge_2.12' (out-18) (out-1)
[info] [error] Total time: 14 s, completed Mar 23, 2017 4:58:11 PM (out-3) (out-1)
```

## expectation

Scala 2.11 is supported.

**Comment by eed3si9n** [comment]
Scala 2.11.2+ works so this could be a false alarm.
Is this because of JDK 8 compat issue? It would be good to know exactly which version of the Scala minor releases are supported and print out error messages.

**Comment by eed3si9n** [comment]
Also note this problem didn't happen in Zinc 1.0.0-X8, so we've somehow regressed in the bridge code?

**Comment by jvican** [comment]
https://github.com/sbt/zinc/pull/243 was probably the culprit.
  
What I don't understand is why we didn't catch this error before... If it fails on 2.11.0 and not in 2.11.x for x greater than 0, it is probably an error in our compat utils.

**Comment by eed3si9n** [comment]
On Zinc build, compiler bridge is only compiled using 2.11.8 for 2.11.x, so we didn't catch it until sbt's integration test tried it with 2.11.0.

For 2.10.x, it also only works for 2.10.2+.

```
error: error while loading CharSequence, class file '/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/rt.jar(java/lang/CharSequence.class)' is broken
(class java.lang.RuntimeException/bad constant pool tag 18 at byte 10)
error: error while loading Comparator, class file '/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/rt.jar(java/util/Comparator.class)' is broken
(class java.lang.RuntimeException/bad constant pool tag 18 at byte 20)
error: error while loading Entry, class file '/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/rt.jar(java/util/Map$Entry.class)' is broken
(class java.lang.RuntimeException/bad constant pool tag 18 at byte 10)
/var/folders/7g/l96y5q310h90xsz109qqjpmc0000gn/T/sbt_737b8339/xsbt/API.scala:45: error: value getKey is not a member of java.util.Map.Entry[String,Array[String]]
        stringBuffer.append(showUsedNames(values.getKey, values.getValue))
                                                 ^
/var/folders/7g/l96y5q310h90xsz109qqjpmc0000gn/T/sbt_737b8339/xsbt/API.scala:59: error: value getKey is not a member of java.util.Map.Entry[String,Array[String]]
        val className = usedNameInfo.getKey
                                     ^
/var/folders/7g/l96y5q310h90xsz109qqjpmc0000gn/T/sbt_737b8339/xsbt/API.scala:60: error: value getValue is not a member of java.util.Map.Entry[String,Array[String]]
        val namesIterator = usedNameInfo.getValue.iterator
                                         ^
error: error while loading AnnotatedElement, class file '/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/rt.jar(java/lang/reflect/AnnotatedElement.class)' is broken
(class java.lang.RuntimeException/bad constant pool tag 18 at byte 76)
error: error while loading Arrays, class file '/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/rt.jar(java/util/Arrays.class)' is broken
(class java.lang.RuntimeException/bad constant pool tag 18 at byte 765)
/var/folders/7g/l96y5q310h90xsz109qqjpmc0000gn/T/sbt_737b8339/xsbt/ExtractAPI.scala:587: error: java.util.Comparator does not take type parameters
  private[this] val sortClasses = new Comparator[Symbol] {
                                      ^
/var/folders/7g/l96y5q310h90xsz109qqjpmc0000gn/T/sbt_737b8339/xsbt/ExtractUsedNames.scala:78: error: value getKey is not a member of java.util.Map.Entry[ExtractUsedNames.this.global.Name,java.util.HashSet[ExtractUsedNames.this.global.Name]]
      val className = usedNamePair.getKey.toString.trim
                                   ^
/var/folders/7g/l96y5q310h90xsz109qqjpmc0000gn/T/sbt_737b8339/xsbt/ExtractUsedNames.scala:79: error: value getValue is not a member of java.util.Map.Entry[ExtractUsedNames.this.global.Name,java.util.HashSet[ExtractUsedNames.this.global.Name]]
      val usedNames = usedNamePair.getValue
                                   ^
```

**Comment by dwijnand** [comment]
@eed3si9n lemme know if 2.11.0 / 2.11.1 support is important enough for zinc / sbt 1 for me to fix this.

**Comment by jvican** [comment]
Honestly, I don't think it is.

**Comment by eed3si9n** [comment]
Yea.
I think it's ok as is probably but we should all be aware of the limitation
and also document / display warning on it.

**Comment by stuhood** [comment]
I see the following failure for `2.10.6` with zinc `1.0.3`: is it expected that zinc would not work with 2.10 either?
```
Non-compiled module 'compiler-interface' for Scala 2.10.6. Compiling...
/tmp/sbt_54f48455/xsbt/ClassName.scala:23: error: not found: value enteringPhase
    enteringPhase(currentRun.flattenPhase.next) { s fullName separator }
    ^
/tmp/sbt_54f48455/xsbt/ClassName.scala:77: error: not found: value enteringPhase
    enteringPhase(currentRun.picklerPhase.next) {
    ^
/tmp/sbt_54f48455/xsbt/ClassName.scala:87: error: not found: value enteringPhase
    enteringPhase(currentRun.picklerPhase.next) { s.fullNameAsName('.') }
    ^
/tmp/sbt_54f48455/xsbt/ClassName.scala:90: error: not found: value enteringPhase
    enteringPhase(currentRun.picklerPhase.next) { s.fullName }
    ^
/tmp/sbt_54f48455/xsbt/ClassName.scala:93: error: not found: value enteringPhase
    enteringPhase(currentRun.picklerPhase.next) {
    ^
/tmp/sbt_54f48455/xsbt/DelegatingReporter.scala:67: error: value finalPosition is not a member of scala.reflect.internal.util.Position
        case _                       => Option(pos.finalPosition)
                                                   ^
/tmp/sbt_54f48455/xsbt/DelegatingReporter.scala:94: error: constructor cannot be instantiated to expected type;
 found   : Some[A]
 required: None.type
      case Some(cleanPos) => makePosition(cleanPos)
           ^
/tmp/sbt_54f48455/xsbt/DelegatingReporter.scala:94: error: missing arguments for method cleanPos;
follow this method with `_' if you want to treat it as a partially applied function
      case Some(cleanPos) => makePosition(cleanPos)
                                          ^
/tmp/sbt_54f48455/xsbt/Dependency.scala:265: error: not found: value devWarning
        else devWarning(Feedback.missingEnclosingClass(dep, currentOwner))
             ^
/tmp/sbt_54f48455/xsbt/Dependency.scala:279: error: not found: value devWarning
          else devWarning(Feedback.missingEnclosingClass(dep, currentOwner))
               ^
/tmp/sbt_54f48455/xsbt/ExtractAPI.scala:219: error: not found: value enteringPhase
    enteringPhase(currentRun.typerPhase) {
    ^
/tmp/sbt_54f48455/xsbt/ExtractAPI.scala:412: error: value getterIn is not a member of ExtractAPI.this.global.Symbol
    val getter = sym.getterIn(sym.enclClass)
                     ^
/tmp/sbt_54f48455/xsbt/ExtractAPI.scala:704: error: value unexpandedName is not a member of ExtractAPI.this.global.Symbol
    val n = s.unexpandedName
              ^
/tmp/sbt_54f48455/xsbt/ExtractUsedNames.scala:277: error: value hasSymbolField is not a member of ExtractUsedNames.this.global.Tree
      case t if t.hasSymbolField =>
                  ^
/tmp/sbt_54f48455/xsbt/GlobalHelpers.scala:136: error: value expandee is not a member of GlobalHelpers.this.global.MacroExpansionAttachment
        func(macroAttachment.expandee)
                             ^
/tmp/sbt_54f48455/xsbt/GlobalHelpers.scala:147: error: value expandee is not a member of GlobalHelpers.this.global.MacroExpansionAttachment
        case att: MacroExpansionAttachment => att.expandee
                                                  ^
16 errors found
com.google.common.util.concurrent.UncheckedExecutionException: Error compiling the sbt component 'compiler-interface'
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4739)
	at org.pantsbuild.zinc.cache.Cache$Implicits.getOrElseUpdate(Cache.scala:34)
	at org.pantsbuild.zinc.compiler.CompilerUtils$.getOrCreate(CompilerUtils.scala:74)
	at org.pantsbuild.zinc.compiler.InputUtils$.create(InputUtils.scala:43)
	at org.pantsbuild.zinc.compiler.Main$.main(Main.scala:105)
	at org.pantsbuild.zinc.compiler.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:280)
Caused by: Error compiling the sbt component 'compiler-interface'
	at sbt.internal.inc.AnalyzingCompiler$.sbt$internal$inc$AnalyzingCompiler$$handleCompilationError$1(AnalyzingCompiler.scala:331)
	at sbt.internal.inc.AnalyzingCompiler$$anonfun$compileSources$1$$anonfun$apply$2.apply(AnalyzingCompiler.scala:346)
	at sbt.internal.inc.AnalyzingCompiler$$anonfun$compileSources$1$$anonfun$apply$2.apply(AnalyzingCompiler.scala:341)
	at sbt.io.IO$.withTemporaryDirectory(IO.scala:332)
	at sbt.io.IO$.withTemporaryDirectory(IO.scala:340)
	at sbt.internal.inc.AnalyzingCompiler$$anonfun$compileSources$1.apply(AnalyzingCompiler.scala:341)
	at sbt.internal.inc.AnalyzingCompiler$$anonfun$compileSources$1.apply(AnalyzingCompiler.scala:335)
	at sbt.io.IO$.withTemporaryDirectory(IO.scala:332)
	at sbt.io.IO$.withTemporaryDirectory(IO.scala:340)
	at sbt.internal.inc.AnalyzingCompiler$.compileSources(AnalyzingCompiler.scala:335)
	at org.pantsbuild.zinc.compiler.CompilerUtils$.compile$1(CompilerUtils.scala:135)
	at org.pantsbuild.zinc.compiler.CompilerUtils$.compilerInterface(CompilerUtils.scala:149)
	at org.pantsbuild.zinc.compiler.CompilerUtils$$anonfun$getOrCreate$1.apply(CompilerUtils.scala:76)
	at org.pantsbuild.zinc.compiler.CompilerUtils$$anonfun$getOrCreate$1.apply(CompilerUtils.scala:74)
	at org.pantsbuild.zinc.cache.Cache$Implicits$$anon$1.call(Cache.scala:34)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4742)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 12 more
```

**Comment by dwijnand** [comment]
@stuhood No it should work, you just need to make sure you include the 2.10 specific sources: https://github.com/sbt/zinc/blob/v1.0.3/internal/compiler-bridge/src/main/scala_2.10/xsbt/Compat.scala#L111.

FWIW here's how that's setup in sbt: https://github.com/sbt/zinc/blob/v1.0.3/build.sbt#L353-L356.

**Comment by stuhood** [comment]
...oho. I think that I had been assuming that the compiler-bridge being cross-versioned was just a mistake! Thanks for that: using the correct compiler-bridge version fixed it.

**Comment by jvican** [comment]
Closing, this issue has been open for quite a while and 2.11.0 is unsupported, 2.11.11 is the recommended version for Scala 2.11 users.

**Comment by ericbellet** [comment]
I have the same problem: 

> Error compiling the sbt component 'compiler-bridge_2.11'

How can I fix this issue?

**Comment by SethTisue** [comment]
@ericbellet based on just that one small fragment of the complete error message being the same, whatever you're experiencing might be the "same" problem, or it might not.

the history above shows that the particular problem in this ticket is believed to have already been fixed for users of recent Scala 2.11.x versions. are you using the latest 2.11.x version, namely (at the time I write) 2.11.12?

**Comment by SethTisue** [comment]
oh, I see you opened https://github.com/sbt/zinc/issues/737 — let's continue there

**Comment by nikhilgupta14** [comment]
closes #737 
@ericbellet If you are still getting the same error you can try putting cross scala versions in **build.sbt** of your project.
Here is the line,
CrossScalaVeresions:= Seq("2.11.8","2.12.4","2.12.8)
