### ISSUE TITLE
ClassNotFoundException: xsbt.DelegatingReporter$CompileProblem

### ISSUE THREAD

**Issue by lukestephenson-zendesk** [sbt/zinc#749]
Using sbt `1.3.8` compiling a Scala `2.13.1` project it fails with the `java.lang.NoClassDefFoundError: xsbt/DelegatingReporter$CompileProblem`.  Note that this project cross compiles with Scala `2.12.11` with no issues.

I'm uncertain why the class cannot be found as it's located in the same file as the `xsbt.DelegatingReporter.info0` method trying to use it. https://github.com/sbt/zinc/blob/f2bb3115dd8459df9e2cd06143c2ce779cd1ba00/internal/compiler-bridge/src/main/scala/xsbt/DelegatingReporter.scala#L196

I'm still investigating, so apologies the bug report is light on details.  I'll add more details as I find them.

The full stack trace is:
```
Step #1 - "publish": [info] Compiling 996 Scala sources to /app/protobuf-publish/scala/target/scala-2.13/classes ...
Step #1 - "publish": [info] Non-compiled module 'compiler-bridge_2.13' for Scala 2.13.1. Compiling...
Step #1 - "publish": 8 warnings found
Step #1 - "publish": [info]   Compilation completed in 20.836s.
Step #1 - "publish": [error] ## Exception when compiling 996 sources to /app/protobuf-publish/scala/target/scala-2.13/classes
Step #1 - "publish": [error] java.lang.NoClassDefFoundError: xsbt/DelegatingReporter$CompileProblem
Step #1 - "publish": [error] xsbt.DelegatingReporter.info0(DelegatingReporter.scala:181)
Step #1 - "publish": [error] scala.tools.nsc.reporters.MakeFilteringForwardingReporter.doReport(ForwardingReporter.scala:59)
Step #1 - "publish": [error] scala.tools.nsc.reporters.FilteringReporter.info0(Reporter.scala:93)
Step #1 - "publish": [error] scala.reflect.internal.Reporter.filteredInfo(Reporting.scala:118)
Step #1 - "publish": [error] scala.reflect.internal.Reporter.warning(Reporting.scala:112)
Step #1 - "publish": [error] scala.tools.nsc.Reporting$PerRunReporting$ConditionalWarning.$anonfun$summarize$2(Reporting.scala:58)
Step #1 - "publish": [error] scala.tools.nsc.Reporting$PerRunReporting$ConditionalWarning.$anonfun$summarize$2$adapted(Reporting.scala:53)
Step #1 - "publish": [error] scala.collection.mutable.RedBlackTree$.foreach(RedBlackTree.scala:440)
Step #1 - "publish": [error] scala.collection.mutable.TreeMap.foreach(TreeMap.scala:135)
Step #1 - "publish": [error] scala.tools.nsc.Reporting$PerRunReporting$ConditionalWarning.summarize(Reporting.scala:53)
Step #1 - "publish": [error] scala.tools.nsc.Reporting$PerRunReporting.summarizeErrors(Reporting.scala:130)
Step #1 - "publish": [error] scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1551)
Step #1 - "publish": [error] scala.tools.nsc.Global$Run.compileUnits(Global.scala:1490)
Step #1 - "publish": [error] scala.tools.nsc.Global$Run.compileSources(Global.scala:1482)
Step #1 - "publish": [error] scala.tools.nsc.Global$Run.compile(Global.scala:1614)
Step #1 - "publish": [error] xsbt.CachedCompiler0.run(CompilerInterface.scala:153)
Step #1 - "publish": [error] xsbt.CachedCompiler0.run(CompilerInterface.scala:125)
Step #1 - "publish": [error] xsbt.CompilerInterface.run(CompilerInterface.scala:39)
Step #1 - "publish": [error] sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Step #1 - "publish": [error] sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Step #1 - "publish": [error] sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Step #1 - "publish": [error] java.lang.reflect.Method.invoke(Method.java:498)
Step #1 - "publish": [error] sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
Step #1 - "publish": [error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:122)
Step #1 - "publish": [error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:95)
Step #1 - "publish": [error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:91)
Step #1 - "publish": [error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
Step #1 - "publish": [error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:186)
Step #1 - "publish": [error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
Step #1 - "publish": [error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3$adapted(MixedAnalyzingCompiler.scala:77)
Step #1 - "publish": [error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:215)
Step #1 - "publish": [error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:77)
Step #1 - "publish": [error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:146)
Step #1 - "publish": [error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:343)
Step #1 - "publish": [error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:343)
Step #1 - "publish": [error] sbt.internal.inc.Incremental$.doCompile(Incremental.scala:120)
Step #1 - "publish": [error] sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:100)
Step #1 - "publish": [error] sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:180)
Step #1 - "publish": [error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:98)
Step #1 - "publish": [error] sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:102)
Step #1 - "publish": [error] sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:155)
Step #1 - "publish": [error] sbt.internal.inc.Incremental$.compile(Incremental.scala:92)
Step #1 - "publish": [error] sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:75)
Step #1 - "publish": [error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:348)
Step #1 - "publish": [error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:301)
Step #1 - "publish": [error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:168)
Step #1 - "publish": [error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:248)
Step #1 - "publish": [error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:74)
Step #1 - "publish": [error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1762)
Step #1 - "publish": [error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1735)
Step #1 - "publish": [error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
Step #1 - "publish": [error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
Step #1 - "publish": [error] sbt.std.Transform$$anon$4.work(Transform.scala:67)
Step #1 - "publish": [error] sbt.Execute.$anonfun$submit$2(Execute.scala:281)
Step #1 - "publish": [error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
Step #1 - "publish": [error] sbt.Execute.work(Execute.scala:290)
Step #1 - "publish": [error] sbt.Execute.$anonfun$submit$1(Execute.scala:281)
Step #1 - "publish": [error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
Step #1 - "publish": [error] sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
Step #1 - "publish": [error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
Step #1 - "publish": [error] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Step #1 - "publish": [error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
Step #1 - "publish": [error] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Step #1 - "publish": [error] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Step #1 - "publish": [error] java.lang.Thread.run(Thread.java:748)
Step #1 - "publish": [error]            
Step #1 - "publish": [error] java.lang.NoClassDefFoundError: xsbt/DelegatingReporter$CompileProblem
Step #1 - "publish": [error] 	at xsbt.DelegatingReporter.info0(DelegatingReporter.scala:181)
Step #1 - "publish": [error] 	at scala.tools.nsc.reporters.MakeFilteringForwardingReporter.doReport(ForwardingReporter.scala:59)
Step #1 - "publish": [error] 	at scala.tools.nsc.reporters.FilteringReporter.info0(Reporter.scala:93)
Step #1 - "publish": [error] 	at scala.reflect.internal.Reporter.filteredInfo(Reporting.scala:118)
Step #1 - "publish": [error] 	at scala.reflect.internal.Reporter.warning(Reporting.scala:112)
Step #1 - "publish": [error] 	at scala.tools.nsc.Reporting$PerRunReporting$ConditionalWarning.$anonfun$summarize$2(Reporting.scala:58)
Step #1 - "publish": [error] 	at scala.tools.nsc.Reporting$PerRunReporting$ConditionalWarning.$anonfun$summarize$2$adapted(Reporting.scala:53)
Step #1 - "publish": [error] 	at scala.collection.mutable.RedBlackTree$.foreach(RedBlackTree.scala:440)
Step #1 - "publish": [error] 	at scala.collection.mutable.TreeMap.foreach(TreeMap.scala:135)
Step #1 - "publish": [error] 	at scala.tools.nsc.Reporting$PerRunReporting$ConditionalWarning.summarize(Reporting.scala:53)
Step #1 - "publish": [error] 	at scala.tools.nsc.Reporting$PerRunReporting.summarizeErrors(Reporting.scala:130)
Step #1 - "publish": [error] 	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1551)
Step #1 - "publish": [error] 	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1490)
Step #1 - "publish": [error] 	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1482)
Step #1 - "publish": [error] 	at scala.tools.nsc.Global$Run.compile(Global.scala:1614)
Step #1 - "publish": [error] 	at xsbt.CachedCompiler0.run(CompilerInterface.scala:153)
Step #1 - "publish": [error] 	at xsbt.CachedCompiler0.run(CompilerInterface.scala:125)
Step #1 - "publish": [error] 	at xsbt.CompilerInterface.run(CompilerInterface.scala:39)
Step #1 - "publish": [error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Step #1 - "publish": [error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Step #1 - "publish": [error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Step #1 - "publish": [error] 	at java.lang.reflect.Method.invoke(Method.java:498)
Step #1 - "publish": [error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
Step #1 - "publish": [error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:122)
Step #1 - "publish": [error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:95)
Step #1 - "publish": [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:91)
Step #1 - "publish": [error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
Step #1 - "publish": [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:186)
Step #1 - "publish": [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
Step #1 - "publish": [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3$adapted(MixedAnalyzingCompiler.scala:77)
Step #1 - "publish": [error] 	at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:215)
Step #1 - "publish": [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:77)
Step #1 - "publish": [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:146)
Step #1 - "publish": [error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:343)
Step #1 - "publish": [error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:343)
Step #1 - "publish": [error] 	at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:120)
Step #1 - "publish": [error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:100)
Step #1 - "publish": [error] 	at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:180)
Step #1 - "publish": [error] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:98)
Step #1 - "publish": [error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:102)
Step #1 - "publish": [error] 	at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:155)
Step #1 - "publish": [error] 	at sbt.internal.inc.Incremental$.compile(Incremental.scala:92)
Step #1 - "publish": [error] 	at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:75)
Step #1 - "publish": [error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:348)
Step #1 - "publish": [error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:301)
Step #1 - "publish": [error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:168)
Step #1 - "publish": [error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:248)
Step #1 - "publish": [error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:74)
Step #1 - "publish": [error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1762)
Step #1 - "publish": [error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1735)
Step #1 - "publish": [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
Step #1 - "publish": [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
Step #1 - "publish": [error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
Step #1 - "publish": [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
Step #1 - "publish": [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
Step #1 - "publish": [error] 	at sbt.Execute.work(Execute.scala:290)
Step #1 - "publish": [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
Step #1 - "publish": [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
Step #1 - "publish": [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
Step #1 - "publish": [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Step #1 - "publish": [error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Step #1 - "publish": [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Step #1 - "publish": [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Step #1 - "publish": [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Step #1 - "publish": [error] 	at java.lang.Thread.run(Thread.java:748)
Step #1 - "publish": [error] Caused by: java.lang.ClassNotFoundException: xsbt.DelegatingReporter$CompileProblem
Step #1 - "publish": [error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
Step #1 - "publish": [error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
Step #1 - "publish": [error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
Step #1 - "publish": [error] 	at xsbt.DelegatingReporter.info0(DelegatingReporter.scala:181)
Step #1 - "publish": [error] 	at scala.tools.nsc.reporters.MakeFilteringForwardingReporter.doReport(ForwardingReporter.scala:59)
Step #1 - "publish": [error] 	at scala.tools.nsc.reporters.FilteringReporter.info0(Reporter.scala:93)
Step #1 - "publish": [error] 	at scala.reflect.internal.Reporter.filteredInfo(Reporting.scala:118)
Step #1 - "publish": [error] 	at scala.reflect.internal.Reporter.warning(Reporting.scala:112)
Step #1 - "publish": [error] 	at scala.tools.nsc.Reporting$PerRunReporting$ConditionalWarning.$anonfun$summarize$2(Reporting.scala:58)
Step #1 - "publish": [error] 	at scala.tools.nsc.Reporting$PerRunReporting$ConditionalWarning.$anonfun$summarize$2$adapted(Reporting.scala:53)
Step #1 - "publish": [error] 	at scala.collection.mutable.RedBlackTree$.foreach(RedBlackTree.scala:440)
Step #1 - "publish": [error] 	at scala.collection.mutable.TreeMap.foreach(TreeMap.scala:135)
Step #1 - "publish": [error] 	at scala.tools.nsc.Reporting$PerRunReporting$ConditionalWarning.summarize(Reporting.scala:53)
Step #1 - "publish": [error] 	at scala.tools.nsc.Reporting$PerRunReporting.summarizeErrors(Reporting.scala:130)
Step #1 - "publish": [error] 	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1551)
Step #1 - "publish": [error] 	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1490)
Step #1 - "publish": [error] 	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1482)
Step #1 - "publish": [error] 	at scala.tools.nsc.Global$Run.compile(Global.scala:1614)
Step #1 - "publish": [error] 	at xsbt.CachedCompiler0.run(CompilerInterface.scala:153)
Step #1 - "publish": [error] 	at xsbt.CachedCompiler0.run(CompilerInterface.scala:125)
Step #1 - "publish": [error] 	at xsbt.CompilerInterface.run(CompilerInterface.scala:39)
Step #1 - "publish": [error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Step #1 - "publish": [error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Step #1 - "publish": [error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Step #1 - "publish": [error] 	at java.lang.reflect.Method.invoke(Method.java:498)
Step #1 - "publish": [error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
Step #1 - "publish": [error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:122)
Step #1 - "publish": [error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:95)
Step #1 - "publish": [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:91)
Step #1 - "publish": [error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
Step #1 - "publish": [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:186)
Step #1 - "publish": [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
Step #1 - "publish": [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3$adapted(MixedAnalyzingCompiler.scala:77)
Step #1 - "publish": [error] 	at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:215)
Step #1 - "publish": [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:77)
Step #1 - "publish": [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:146)
Step #1 - "publish": [error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:343)
Step #1 - "publish": [error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:343)
Step #1 - "publish": [error] 	at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:120)
Step #1 - "publish": [error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:100)
Step #1 - "publish": [error] 	at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:180)
Step #1 - "publish": [error] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:98)
Step #1 - "publish": [error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:102)
Step #1 - "publish": [error] 	at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:155)
Step #1 - "publish": [error] 	at sbt.internal.inc.Incremental$.compile(Incremental.scala:92)
Step #1 - "publish": [error] 	at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:75)
Step #1 - "publish": [error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:348)
Step #1 - "publish": [error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:301)
Step #1 - "publish": [error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:168)
Step #1 - "publish": [error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:248)
Step #1 - "publish": [error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:74)
Step #1 - "publish": [error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1762)
Step #1 - "publish": [error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1735)
Step #1 - "publish": [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
Step #1 - "publish": [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
Step #1 - "publish": [error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
Step #1 - "publish": [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
Step #1 - "publish": [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
Step #1 - "publish": [error] 	at sbt.Execute.work(Execute.scala:290)
Step #1 - "publish": [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
Step #1 - "publish": [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
Step #1 - "publish": [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
Step #1 - "publish": [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Step #1 - "publish": [error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Step #1 - "publish": [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Step #1 - "publish": [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Step #1 - "publish": [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Step #1 - "publish": [error] 	at java.lang.Thread.run(Thread.java:748)
Step #1 - "publish": [error] (Compile / compileIncremental) java.lang.NoClassDefFoundError: xsbt/DelegatingReporter$CompileProblem
Step #1 - "publish": [error] Total time: 310 s (05:10), completed Mar 25, 2020 11:25:01 PM
```

**Comment by asoltysik** [comment]
I've had the same exact error appear in my CI. Deleting the following sbt plugins helped (kinda... now I have a different error).

```
"com.orrsella" % "sbt-stats" % "1.0.7"
"org.scoverage" % "sbt-scoverage" % "1.6.1"
"net.virtual-void" % "sbt-dependency-graph" % "0.9.2"
```

Also updating scalafmt from
```
"com.lucidchart" % "sbt-scalafmt" % "1.16"
```
to the official one
```
"org.scalameta" % "sbt-scalafmt" % "2.3.2"
```

See if removing any of these help.

**Comment by ambantis** [comment]
@lukestephenson-zendesk @asoltysik any updates on this?

**Comment by lukestephenson-zendesk** [comment]
I'm no longer affected by this issue. Will close.
