### ISSUE TITLE
"sbt '++ 2.13.0-M2!' compile" does not work with sbt 1.0.0

### ISSUE THREAD

**Issue by eed3si9n** [sbt/zinc#395]
Originally reported by @xuwei-k as https://github.com/sbt/sbt/issues/3427

```scala
/tmp/sbt_a4c7a1d5/xsbt/ConsoleInterface.scala:11: error: object ILoop is not a member of package scala.tools.nsc.interpreter
import scala.tools.nsc.interpreter.{ ILoop, IMain, InteractiveReader }
       ^
/tmp/sbt_a4c7a1d5/xsbt/ConsoleInterface.scala:41: error: not found: type ILoop
    val loop = new ILoop {
                   ^
```

We need a new compiler bridge for Scala 2.13.

/cc @lrytz

**Comment by xuwei-k** [comment]
`ILoop.scala` moved to `scala.tools.nsc.interpreter.shell` from `scala.tools.nsc.interpreter` in https://github.com/scala/scala/commit/3de08541f259b4101f050086dfa2c43ba27c0195#diff-90fb2af3c2b08b4164f4212c5b6ab353

**Comment by dwijnand** [comment]
Fixed in https://github.com/sbt/zinc/pull/453, it'll be part of zinc 1.0.4 and sbt 1.0.4.
