### ISSUE TITLE
Clean/recompile on every new sbt incarnation on JDK 11

### ISSUE THREAD

**Issue by johanandren** [sbt/zinc#622]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## problem
Can't say for sure, but, potentially appeared after we upgraded to 1.2.3 in the Akka project.

Whenever I start a new instance of sbt in the Akka project, and do something that triggers a compile, I get this error:

```
akka > akka-actor-typed-tests/compile
[info] Formatting 1 Scala source ProjectRef(uri("file:/Users/johan/Code/Lightbend/Akka/akka-master/"), "akka-actor")(compile) ...
[info] Compiling 9 Scala sources to /Users/johan/Code/Lightbend/Akka/akka-master/akka-actor/target/classes ...
[error] Symbol 'type akka.pattern.AskSupport' is missing from the classpath.
[error] This symbol is required by 'package akka.pattern.package'.
[error] Make sure that type AskSupport is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'package.class' was compiled against an incompatible version of akka.pattern.
[error] one error found
[error] (akka-actor / Compile / compileIncremental) Compilation failed
[error] Total time: 2 s, completed 21 Sep 2018, 16:01:42
```

Doing a `clean` and then recompiling everything is a workaround. While I then have the sbt instance running incremental compilation works just fine as far as I can see.

Seems to only happen on Java 10 actually, if I switch to Java 8 it works as expected.

## expectation
That I didn't have to do a clean/recompile on each start

## notes
sbt version: 1.2.3
Java version: "10" 2018-03-20

**Comment by eed3si9n** [comment]
@johanandren @helena Do you remember what kind of change you made to trigger this?

I made change like this:

```diff
--- a/akka-actor/src/main/scala/akka/pattern/AskSupport.scala
+++ b/akka-actor/src/main/scala/akka/pattern/AskSupport.scala
@@ -80,8 +80,10 @@ trait AskSupport {
   def ask(actorRef: ActorRef, message: Any)(implicit timeout: Timeout): Future[Any] =
     actorRef.internalAsk(message, timeout, ActorRef.noSender)
   def ask(actorRef: ActorRef, message: Any, sender: ActorRef)(implicit timeout: Timeout): Future[Any] =
-    actorRef.internalAsk(message, timeout, sender)
-
+    {
+      println("1")
+      actorRef.internalAsk(message, timeout, sender)
+    }
   /**
    * Import this implicit conversion to gain `?` and `ask` methods on
    * [[akka.actor.ActorSelection]], which will defer to the
```

and in my JDK 11 Docker image it seems to compile ok:

```
akka > akka-actor-typed-tests/compile
[info] Formatting 1 Scala source ProjectRef(uri("file:/opt/workspace/akka/"), "akka-actor")(compile) ...
[info] Compiling 3 Scala sources to /opt/workspace/akka/akka-actor/target/classes ...
[warn] /opt/workspace/akka/akka-actor/src/main/scala/akka/pattern/AskSupport.scala:500:21: private var _stateDoNotCallMeDirectly in class PromiseActorRef is never used
[warn]   private[this] var _stateDoNotCallMeDirectly: AnyRef = _
[warn]                     ^
[warn] /opt/workspace/akka/akka-actor/src/main/scala/akka/pattern/AskSupport.scala:503:21: private var _watchedByDoNotCallMeDirectly in class PromiseActorRef is never used
[warn]   private[this] var _watchedByDoNotCallMeDirectly: Set[ActorRef] = ActorCell.emptyActorRefSet
[warn]                     ^
[warn] two warnings found
[info] Done compiling.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/home/demiourgos1/.sbt/boot/scala-2.12.7/org.scala-sbt/sbt/1.2.8/protobuf-java-3.3.1.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[success] Total time: 8 s, completed Feb 18, 2019, 2:41:04 AM
```

**Comment by eed3si9n** [comment]
Actually I was able to reproduce the issue using the above diff on macOS, but after several tries.

```
[debug] Modified text of file is:
[debug] None
[debug] Copy resource mappings:
[debug] 	(/Users/eed3si9n/work/akka/akka-actor-typed/src/main/resources/reference.conf,/Users/eed3si9n/work/akka/akka-actor-typed/target/classes/reference.conf)
[debug] Copy resource mappings:
[debug] 	(/Users/eed3si9n/work/akka/akka-actor/target/resource_managed/main/version.conf,/Users/eed3si9n/work/akka/akka-actor/target/classes/version.conf)
[debug] 	(/Users/eed3si9n/work/akka/akka-actor/src/main/resources/reference.conf,/Users/eed3si9n/work/akka/akka-actor/target/classes/reference.conf)
[debug] Copy resource mappings:
[debug] 	(/Users/eed3si9n/work/akka/akka-testkit/src/main/resources/reference.conf,/Users/eed3si9n/work/akka/akka-testkit/target/classes/reference.conf)
[debug] Copy resource mappings:
[debug] 	(/Users/eed3si9n/work/akka/akka-actor-testkit-typed/src/main/resources/reference.conf,/Users/eed3si9n/work/akka/akka-actor-testkit-typed/target/classes/reference.conf)
[debug] Found 2 template files in /Users/eed3si9n/work/akka/akka-actor/src/main/boilerplate.
[debug] Template 'Tuples.scala.template' older than target. Ignoring.
[debug] Template 'Functions.scala.template' older than target. Ignoring.
[debug] Invalidating /Users/eed3si9n/.jabba/jdk/adopt@1.8.192-12/Contents/Home/jre/lib/rt.jar: class sun.misc.Unsafe now provided by /Users/eed3si9n/dotfiles/sbt/0.13/java9-rt-ext-oracle_corporation_11/rt.jar
[debug]
[debug] Initial source changes:
[debug] 	removed:Set()
[debug] 	added: Set()
[debug] 	modified: Set()
[debug] Invalidated products: Set()
[debug] External API changes: API Changes: Set()
[debug] Modified binary dependencies: Set(/Users/eed3si9n/.jabba/jdk/adopt@1.8.192-12/Contents/Home/jre/lib/rt.jar)
[debug] Initial directly invalidated classes: Set()
[debug]
[debug] Sources indirectly invalidated by:
[debug] 	product: Set()
[debug] 	binary dep: Set(/Users/eed3si9n/work/akka/akka-actor/src/main/scala/akka/actor/RepointableActorRef.scala, /Users/eed3si9n/work/akka/akka-actor/src/main/scala/akka/actor/dungeon/Children.scala, /Users/eed3si9n/work/akka/akka-actor/src/main/scala/akka/pattern/AskSupport.scala, /Users/eed3si9n/work/akka/akka-actor/src/main/scala/akka/dispatch/AbstractDispatcher.scala, /Users/eed3si9n/work/akka/akka-actor/src/main/scala/akka/actor/LightArrayRevolverScheduler.scala, /Users/eed3si9n/work/akka/akka-actor/src/main/scala/akka/pattern/CircuitBreaker.scala, /Users/eed3si9n/work/akka/akka-actor/src/main/scala/akka/actor/dungeon/Dispatch.scala, /Users/eed3si9n/work/akka/akka-actor/src/main/scala/akka/dispatch/Mailbox.scala)
[debug] 	external source: Set()
[debug] All initially invalidated classes: Set()
[debug] All initially invalidated sources:Set(/Users/eed3si9n/work/akka/akka-actor/src/main/scala/akka/actor/RepointableActorRef.scala, /Users/eed3si9n/work/akka/akka-actor/src/main/scala/akka/actor/dungeon/Children.scala, /Users/eed3si9n/work/akka/akka-actor/src/main/scala/akka/pattern/AskSupport.scala, /Users/eed3si9n/work/akka/akka-actor/src/main/scala/akka/dispatch/AbstractDispatcher.scala, /Users/eed3si9n/work/akka/akka-actor/src/main/scala/akka/actor/LightArrayRevolverScheduler.scala, /Users/eed3si9n/work/akka/akka-actor/src/main/scala/akka/pattern/CircuitBreaker.scala, /Users/eed3si9n/work/akka/akka-actor/src/main/scala/akka/actor/dungeon/Dispatch.scala, /Users/eed3si9n/work/akka/akka-actor/src/main/scala/akka/dispatch/Mailbox.scala)
[info] Compiling 8 Scala sources to /Users/eed3si9n/work/akka/akka-actor/target/classes ...
[debug] Getting org.scala-sbt:compiler-bridge_2.12:1.2.4:compile for Scala 2.12.8
[debug] Getting org.scala-sbt:compiler-bridge_2.12:1.2.4:compile for Scala 2.12.8
[debug] [zinc] Running cached compiler 78ae5304 for Scala compiler version 2.12.8
[debug] [zinc] The Scala compiler is invoked with:
[debug] 	-encoding
[debug] 	UTF-8
[debug] 	-feature
[debug] 	-unchecked
[debug] 	-Xlog-reflective-calls
[debug] 	-Xlint
[debug] 	-Ywarn-unused
[debug] 	-release
[debug] 	8
[debug] 	-javabootclasspath
[debug] 	/Users/eed3si9n/.jabba/jdk/adopt@1.8.192-12/Contents/Home/jre/lib/rt.jar
[debug] 	-bootclasspath
[debug] 	/Users/eed3si9n/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.12.8.jar
[debug] 	-classpath
[debug] 	/Users/eed3si9n/work/akka/akka-actor/target/classes:/Users/eed3si9n/.ivy2/cache/com.typesafe/config/bundles/config-1.3.3.jar:/Users/eed3si9n/.ivy2/cache/org.scala-lang.modules/scala-java8-compat_2.12/bundles/scala-java8-compat_2.12-0.8.0.jar
[error] Symbol 'type akka.pattern.AskSupport' is missing from the classpath.
[error] This symbol is required by 'package akka.pattern.package'.
[error] Make sure that type AskSupport is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'package.class' was compiled against an incompatible version of akka.pattern.
[error] one error found
[debug] Compilation failed (CompilerInterface)
[error] (akka-actor / Compile / compileIncremental) Compilation failed
```

Even when the compilation succeeded I noticed that it compiled more than 3 Scala sources, so some false invalidation is happening likely around `Invalidating /Users/eed3si9n/.jabba/jdk/adopt@1.8.192-12/Contents/Home/jre/lib/rt.jar: class sun.misc.Unsafe now provided by /Users/eed3si9n/dotfiles/sbt/0.13/java9-rt-ext-oracle_corporation_11/rt.jar`.

I wonder if this bug is specific problem with Akka's build passing in `-javabootclasspath` in https://github.com/akka/akka/blob/v2.5.19/project/AkkaBuild.scala#L108 and sbt assuming reuse of Java runtime and using layered classloader. /cc @eatkins

**Comment by eatkins** [comment]
I'd have to look at this further, but it seems like this could be handled in the zinc ExternalHooks.

**Comment by johanandren** [comment]
No change at all, I just killed sbt, started a new instance and the next time I trigger compile in any way causes it. 

Alpakka team mentioned **not** having that problem on 11 though, so it may be specific to something in the Akka build like you say.

**Comment by helena** [comment]
@johanandren @eed3si9n I'm fairly sure that I've seen this since before the SBT 1.2.3 upgrade in Akka. When I first saw it I hunted around and found an existing GitHub issue noting others had seen it. But I do see it every time re-starting SBT shell.

Related
- https://github.com/sbt/sbt/issues/3187
- https://github.com/scala/bug/issues/10306

**Comment by helena** [comment]
A bit more deets on weird replication: I was just blocked by it in sbt running `Seq(actorTests)` and this went away by running `Seq(actor, actorTests)`. Have to ponder further.

**Comment by raboof** [comment]
I can still reliably reproduce it under jdk11 by just restarting sbt, no code changes, just compiling the akka-actor subproject.

One interesting thing I noticed: after restarting sbt, before running `compile`, the .class files are right there in the target directory. When running `compile`, `AskSupport.class` briefly disappears, but then immediately reappears with the exact same timestamp as before. Not sure if that is expected?

```
$ ls -alFh ./akka-actor/target/classes/akka/pattern/AskSupport.class ./akka-actor/target/classes/akka/pattern/package.class
-rw-r--r-- 1 aengelen aengelen 5.0K Apr 18 14:45 ./akka-actor/target/classes/akka/pattern/AskSupport.class
-rw-r--r-- 1 aengelen aengelen 4.9K Apr 18 14:45 ./akka-actor/target/classes/akka/pattern/package.class
$ ls -alFh ./akka-actor/target/classes/akka/pattern/AskSupport.class ./akka-actor/target/classes/akka/pattern/package.class
ls: cannot access './akka-actor/target/classes/akka/pattern/AskSupport.class': No such file or directory
-rw-r--r-- 1 aengelen aengelen 4.9K Apr 18 14:45 ./akka-actor/target/classes/akka/pattern/package.class
$ ls -alFh ./akka-actor/target/classes/akka/pattern/AskSupport.class ./akka-actor/target/classes/akka/pattern/package.class
-rw-r--r-- 1 aengelen aengelen 5.0K Apr 18 14:45 ./akka-actor/target/classes/akka/pattern/AskSupport.class
-rw-r--r-- 1 aengelen aengelen 4.9K Apr 18 14:45 ./akka-actor/target/classes/akka/pattern/package.class
```

**Comment by raboof** [comment]
> @eed3si9n 
> so some false invalidation is happening likely around Invalidating /Users/eed3si9n/.jabba/jdk/adopt@1.8.192-12/Contents/Home/jre/lib/rt.jar: class sun.misc.Unsafe now provided by /Users/eed3si9n/dotfiles/sbt/0.13/java9-rt-ext-oracle_corporation_11/rt.jar.
> 
> I wonder if this bug is specific problem with Akka's build passing in -javabootclasspath in https://github.com/akka/akka/blob/v2.5.19/project/AkkaBuild.scala#L108 and sbt assuming reuse of Java runtime and using layered classloader. /cc @eatkins

I removed that flag in https://github.com/akka/akka/tree/withoutJavaBootClasspath and indeed with that change I can no longer reproduce the problem.

That flag is kind of questionable anyway - shouldn't `-release 8` be sufficient?

**Comment by eed3si9n** [comment]
Collecting some more hints.
- https://github.com/sbt/sbt-launcher-package/pull/143 added `-Dscala.ext.dirs=${java9_ext}`, where java9_ext looks like `~/.sbt/0.13/java9-rt-ext-oracle_corporation_11`. This is because "Scala compiler versions prior to 2.12.1 do not tolerate the absence of rt.jar from the JDK." (https://github.com/sbt/sbt/pull/2951)
- `-Dscala.ext.dirs` is picked up by https://github.com/scala/scala/blob/v2.12.8/src/compiler/scala/tools/util/PathResolver.scala
- On sbt side, `ScalaInstance` is created, which is JARs and classloaders used for `compile` task. ( https://github.com/sbt/sbt/blob/c3f9ba1e6edbd8d050f76b22878132c4634123a7/main/src/main/scala/sbt/Defaults.scala#L687-L700). In case the Scala version matches up with the Scala version used by sbt, it will reuse the class loader.
- Akka's build specifies `-javabootclasspath` as noted above.

**Comment by eatkins** [comment]
Yes, I've seen stuff like this before. For sbt 1.3.0, I tried to fix it by excluding jars in the java home: https://github.com/sbt/sbt/blob/cd7d42db76db09463a8ac67921980d8528ef4988/main/src/main/scala/sbt/internal/ExternalHooks.scala#L84. Based on the logs above, I think the new external hooks should correctly not invalidate rt.jar, but I'll try and find time to test with akka and a local version of sbt using the latest code.

**Comment by patriknw** [comment]
Another data point. I can reproduce this without switching branches or changing any source. With JDK 11.

Created a main app in akka-cluster/src/main/scala/akka/cluster/sample/SimpleClusterApp.scala
Running it with
```
sbt "akka-cluster/runMain akka.cluster.sample.SimpleClusterApp 2551"

[error] Symbol 'type akka.pattern.AskSupport' is missing from the classpath.
[error] This symbol is required by 'package akka.pattern.package'.
[error] Make sure that type AskSupport is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'package.class' was compiled against an incompatible version of akka.pattern.
```

Same thing after `clean` and `compile`.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/4679
